import type { BoardPack, Card, Square } from '../types';

/**
 * Parkway Classic — the city of Ashvale.
 *
 * Forty squares, eight colour groups, four stations, two utilities. The names,
 * the group names and every word of card text are original to this project. The
 * numbers are not: prices, rent tables, build costs, mortgage values, bank supply
 * and fines match the standard game exactly, because the numbers are what make
 * the board feel right to someone who already knows how to play (→ D16).
 *
 * Ashvale reads outward from the river. The tanneries and kilns sit at the
 * bottom of the board, the foundries and market halls in the middle, and the
 * cathedral close at the top.
 */

const squares: readonly Square[] = [
  { kind: 'start', id: 0, name: 'The Parkway' },
  {
    kind: 'property',
    id: 1,
    name: 'Tannery Row',
    group: 'group-1',
    price: 60,
    mortgageValue: 30,
    buildCost: 50,
    rent: [2, 10, 30, 90, 160, 250],
  },
  { kind: 'card', id: 2, name: 'Civic Fund', deck: 'chest' },
  {
    kind: 'property',
    id: 3,
    name: 'Kiln Lane',
    group: 'group-1',
    price: 60,
    mortgageValue: 30,
    buildCost: 50,
    rent: [4, 20, 60, 180, 320, 450],
  },
  { kind: 'tax', id: 4, name: 'Revenue Assessment', flatAmount: 200, percentageRate: 0.1 },
  { kind: 'transit', id: 5, name: 'Northgate Station', price: 200, mortgageValue: 100 },
  {
    kind: 'property',
    id: 6,
    name: 'Ferry Approach',
    group: 'group-2',
    price: 100,
    mortgageValue: 50,
    buildCost: 50,
    rent: [6, 30, 90, 270, 400, 550],
  },
  { kind: 'card', id: 7, name: 'Fortune', deck: 'chance' },
  {
    kind: 'property',
    id: 8,
    name: 'Saltmarsh Walk',
    group: 'group-2',
    price: 100,
    mortgageValue: 50,
    buildCost: 50,
    rent: [6, 30, 90, 270, 400, 550],
  },
  {
    kind: 'property',
    id: 9,
    name: 'Cobb Street',
    group: 'group-2',
    price: 120,
    mortgageValue: 60,
    buildCost: 50,
    rent: [8, 40, 100, 300, 450, 600],
  },
  { kind: 'jail', id: 10, name: 'Ashvale Gaol' },
  {
    kind: 'property',
    id: 11,
    name: 'Weavers Gate',
    group: 'group-3',
    price: 140,
    mortgageValue: 70,
    buildCost: 100,
    rent: [10, 50, 150, 450, 625, 750],
  },
  { kind: 'utility', id: 12, name: 'Riverhead Waterworks', price: 150, mortgageValue: 75 },
  {
    kind: 'property',
    id: 13,
    name: 'Print Yard',
    group: 'group-3',
    price: 140,
    mortgageValue: 70,
    buildCost: 100,
    rent: [10, 50, 150, 450, 625, 750],
  },
  {
    kind: 'property',
    id: 14,
    name: 'Bellrope Lane',
    group: 'group-3',
    price: 160,
    mortgageValue: 80,
    buildCost: 100,
    rent: [12, 60, 180, 500, 700, 900],
  },
  { kind: 'transit', id: 15, name: 'Eastdock Station', price: 200, mortgageValue: 100 },
  {
    kind: 'property',
    id: 16,
    name: 'Foundry Bank',
    group: 'group-4',
    price: 180,
    mortgageValue: 90,
    buildCost: 100,
    rent: [14, 70, 200, 550, 750, 950],
  },
  { kind: 'card', id: 17, name: 'Civic Fund', deck: 'chest' },
  {
    kind: 'property',
    id: 18,
    name: 'Ironmonger Row',
    group: 'group-4',
    price: 180,
    mortgageValue: 90,
    buildCost: 100,
    rent: [14, 70, 200, 550, 750, 950],
  },
  {
    kind: 'property',
    id: 19,
    name: 'Culvert Street',
    group: 'group-4',
    price: 200,
    mortgageValue: 100,
    buildCost: 100,
    rent: [16, 80, 220, 600, 800, 1000],
  },
  { kind: 'free_parking', id: 20, name: 'Marsh Common' },
  {
    kind: 'property',
    id: 21,
    name: 'Almsgate',
    group: 'group-5',
    price: 220,
    mortgageValue: 110,
    buildCost: 150,
    rent: [18, 90, 250, 700, 875, 1050],
  },
  { kind: 'card', id: 22, name: 'Fortune', deck: 'chance' },
  {
    kind: 'property',
    id: 23,
    name: 'Lantern Hill',
    group: 'group-5',
    price: 220,
    mortgageValue: 110,
    buildCost: 150,
    rent: [18, 90, 250, 700, 875, 1050],
  },
  {
    kind: 'property',
    id: 24,
    name: 'Corn Exchange',
    group: 'group-5',
    price: 240,
    mortgageValue: 120,
    buildCost: 150,
    rent: [20, 100, 300, 750, 925, 1100],
  },
  { kind: 'transit', id: 25, name: 'Southbank Station', price: 200, mortgageValue: 100 },
  {
    kind: 'property',
    id: 26,
    name: 'Observatory Rise',
    group: 'group-6',
    price: 260,
    mortgageValue: 130,
    buildCost: 150,
    rent: [22, 110, 330, 800, 975, 1150],
  },
  {
    kind: 'property',
    id: 27,
    name: 'Palm House Walk',
    group: 'group-6',
    price: 260,
    mortgageValue: 130,
    buildCost: 150,
    rent: [22, 110, 330, 800, 975, 1150],
  },
  { kind: 'utility', id: 28, name: 'Kilnfield Power Station', price: 150, mortgageValue: 75 },
  {
    kind: 'property',
    id: 29,
    name: 'Regatta Terrace',
    group: 'group-6',
    price: 280,
    mortgageValue: 140,
    buildCost: 150,
    rent: [24, 120, 360, 850, 1025, 1200],
  },
  { kind: 'go_to_jail', id: 30, name: "Magistrates' Court" },
  {
    kind: 'property',
    id: 31,
    name: 'Charterhouse Green',
    group: 'group-7',
    price: 300,
    mortgageValue: 150,
    buildCost: 200,
    rent: [26, 130, 390, 900, 1100, 1275],
  },
  {
    kind: 'property',
    id: 32,
    name: 'Vellum Court',
    group: 'group-7',
    price: 300,
    mortgageValue: 150,
    buildCost: 200,
    rent: [26, 130, 390, 900, 1100, 1275],
  },
  { kind: 'card', id: 33, name: 'Civic Fund', deck: 'chest' },
  {
    kind: 'property',
    id: 34,
    name: "Merchant's Reach",
    group: 'group-7',
    price: 320,
    mortgageValue: 160,
    buildCost: 200,
    rent: [28, 150, 450, 1000, 1200, 1400],
  },
  { kind: 'transit', id: 35, name: 'Westhill Station', price: 200, mortgageValue: 100 },
  { kind: 'card', id: 36, name: 'Fortune', deck: 'chance' },
  {
    kind: 'property',
    id: 37,
    name: 'Cathedral Close',
    group: 'group-8',
    price: 350,
    mortgageValue: 175,
    buildCost: 200,
    rent: [35, 175, 500, 1100, 1300, 1500],
  },
  { kind: 'tax', id: 38, name: 'Excise Duty', flatAmount: 100, percentageRate: null },
  {
    kind: 'property',
    id: 39,
    name: 'Ashvale Crescent',
    group: 'group-8',
    price: 400,
    mortgageValue: 200,
    buildCost: 200,
    rent: [50, 200, 600, 1400, 1700, 2000],
  },
];

const chance: readonly Card[] = [
  {
    id: 'chance-01',
    deck: 'chance',
    text: 'The Parkway reopens after resurfacing. Advance to the start.',
    effect: { kind: 'move_to', squareId: 0 },
  },
  {
    id: 'chance-02',
    deck: 'chance',
    text: 'The Corn Exchange calls an emergency session. Advance there.',
    effect: { kind: 'move_to', squareId: 24 },
  },
  {
    id: 'chance-03',
    deck: 'chance',
    text: 'You are summoned to Weavers Gate. Advance there.',
    effect: { kind: 'move_to', squareId: 11 },
  },
  {
    id: 'chance-04',
    deck: 'chance',
    text: 'A meter reader finds ten years of arrears. Advance to the nearest utility and pay ten times your roll.',
    effect: { kind: 'move_to_nearest', target: 'utility' },
  },
  {
    id: 'chance-05',
    deck: 'chance',
    text: 'Your season ticket is revoked. Advance to the nearest station and pay double the fare.',
    effect: { kind: 'move_to_nearest', target: 'transit' },
  },
  {
    id: 'chance-06',
    deck: 'chance',
    text: 'The last train is leaving. Advance to the nearest station and pay double the fare.',
    effect: { kind: 'move_to_nearest', target: 'transit' },
  },
  {
    id: 'chance-07',
    deck: 'chance',
    text: 'Harbour bonds pay out. Collect £50.',
    effect: { kind: 'collect', amount: 50 },
  },
  {
    id: 'chance-08',
    deck: 'chance',
    text: 'A clerical error clears your name. Keep this card until you need to leave the gaol.',
    effect: { kind: 'get_out_of_jail' },
  },
  {
    id: 'chance-09',
    deck: 'chance',
    text: 'You have overshot your turning. Go back three squares.',
    effect: { kind: 'move_relative', offset: -3 },
  },
  {
    id: 'chance-10',
    deck: 'chance',
    text: 'The magistrate has seen enough. Go directly to the gaol.',
    effect: { kind: 'go_to_jail' },
  },
  {
    id: 'chance-11',
    deck: 'chance',
    text: 'The surveyor condemns your roofs. Pay £25 for each house and £100 for each hotel.',
    effect: { kind: 'repairs', perHouse: 25, perHotel: 100 },
  },
  {
    id: 'chance-12',
    deck: 'chance',
    text: 'Cited for racing on the embankment. Pay £15.',
    effect: { kind: 'pay', amount: 15 },
  },
  {
    id: 'chance-13',
    deck: 'chance',
    text: 'A goods contract takes you north. Advance to Northgate Station.',
    effect: { kind: 'move_to', squareId: 5 },
  },
  {
    id: 'chance-14',
    deck: 'chance',
    text: 'The Crescent commission is yours. Advance to Ashvale Crescent.',
    effect: { kind: 'move_to', squareId: 39 },
  },
  {
    id: 'chance-15',
    deck: 'chance',
    text: 'You are elected to the drainage board. Pay every other player £50.',
    effect: { kind: 'pay_each_player', amount: 50 },
  },
  {
    id: 'chance-16',
    deck: 'chance',
    text: 'Your building loan matures. Collect £150.',
    effect: { kind: 'collect', amount: 150 },
  },
];

const chest: readonly Card[] = [
  {
    id: 'chest-01',
    deck: 'chest',
    text: 'The city settles its accounts. Advance to the start.',
    effect: { kind: 'move_to', squareId: 0 },
  },
  {
    id: 'chest-02',
    deck: 'chest',
    text: 'A ledger error runs in your favour. Collect £200.',
    effect: { kind: 'collect', amount: 200 },
  },
  {
    id: 'chest-03',
    deck: 'chest',
    text: "The surgeon's bill arrives. Pay £50.",
    effect: { kind: 'pay', amount: 50 },
  },
  {
    id: 'chest-04',
    deck: 'chest',
    text: 'You sell your share in the ferry company. Collect £50.',
    effect: { kind: 'collect', amount: 50 },
  },
  {
    id: 'chest-05',
    deck: 'chest',
    text: 'A friend on the bench owes you a favour. Keep this card until you need to leave the gaol.',
    effect: { kind: 'get_out_of_jail' },
  },
  {
    id: 'chest-06',
    deck: 'chest',
    text: 'You are found to have been trading without a licence. Go directly to the gaol.',
    effect: { kind: 'go_to_jail' },
  },
  {
    id: 'chest-07',
    deck: 'chest',
    text: 'The winter fund matures. Collect £100.',
    effect: { kind: 'collect', amount: 100 },
  },
  {
    id: 'chest-08',
    deck: 'chest',
    text: 'Your assessment is revised downward. Collect £20.',
    effect: { kind: 'collect', amount: 20 },
  },
  {
    id: 'chest-09',
    deck: 'chest',
    text: 'It is your name day. Collect £10 from every other player.',
    effect: { kind: 'collect_from_each_player', amount: 10 },
  },
  {
    id: 'chest-10',
    deck: 'chest',
    text: 'An old policy pays out. Collect £100.',
    effect: { kind: 'collect', amount: 100 },
  },
  {
    id: 'chest-11',
    deck: 'chest',
    text: 'A week in the infirmary. Pay £100.',
    effect: { kind: 'pay', amount: 100 },
  },
  {
    id: 'chest-12',
    deck: 'chest',
    text: 'The grammar school raises its fees. Pay £50.',
    effect: { kind: 'pay', amount: 50 },
  },
  {
    id: 'chest-13',
    deck: 'chest',
    text: 'You are retained to value a warehouse. Collect £25.',
    effect: { kind: 'collect', amount: 25 },
  },
  {
    id: 'chest-14',
    deck: 'chest',
    text: 'The parish levies for road repairs. Pay £40 for each house and £115 for each hotel.',
    effect: { kind: 'repairs', perHouse: 40, perHotel: 115 },
  },
  {
    id: 'chest-15',
    deck: 'chest',
    text: 'Second place at the flower show. Collect £10.',
    effect: { kind: 'collect', amount: 10 },
  },
  {
    id: 'chest-16',
    deck: 'chest',
    text: 'A distant aunt remembers you. Collect £100.',
    effect: { kind: 'collect', amount: 100 },
  },
];

export const parkwayClassic: BoardPack = {
  id: 'parkway-classic',
  name: 'Ashvale',
  currencySymbol: '£',
  squares,
  groups: [
    { id: 'group-1', name: 'The Tanneries', colourToken: 'group-1', memberIds: [1, 3] },
    { id: 'group-2', name: 'Ferryside', colourToken: 'group-2', memberIds: [6, 8, 9] },
    { id: 'group-3', name: 'Weavers Quarter', colourToken: 'group-3', memberIds: [11, 13, 14] },
    { id: 'group-4', name: 'Foundry District', colourToken: 'group-4', memberIds: [16, 18, 19] },
    { id: 'group-5', name: 'Old Market', colourToken: 'group-5', memberIds: [21, 23, 24] },
    { id: 'group-6', name: 'Observatory Hill', colourToken: 'group-6', memberIds: [26, 27, 29] },
    { id: 'group-7', name: 'Charterhouse', colourToken: 'group-7', memberIds: [31, 32, 34] },
    { id: 'group-8', name: 'The Close', colourToken: 'group-8', memberIds: [37, 39] },
  ],
  transit: { rentByCount: [25, 50, 100, 200], cardPenaltyMultiplier: 2 },
  utility: { multiplierByCount: [4, 10], cardPenaltyMultiplier: 10 },
  bank: { houses: 32, hotels: 12 },
  auction: { minimumIncrement: 10 },
  jail: { squareId: 10, fine: 50, maxTurns: 3 },
  startSquareId: 0,
  goToJailSquareId: 30,
  mortgageInterestRate: 0.1,
  housesPerHotel: 4,
  dice: { count: 2, faces: 6 },
  decks: { chance, chest },
};
